// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "IndexPage": {
    "title": "next-intl example"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "Navigation": {
    "home": "HOME",
    "about": "ABOUT",
    "product": "PRODUCT",
    "subMenuHeading": {
      "area": "Area",
      "products": "Products",
      "typeOfApartments": "Types of Apartments"
    },
    "blogs": "BLOGS",
    "contact": "CONTACT",
    "position": "Nguyễn Anh Tú Investment Consultant"
  },
  "Footer": {
    "home": "Home",
    "about": "About",
    "product": "Product",
    "blogs": "Blogs",
    "contact": "Contact",
    "privacyPolicy": "Privacy Policy",
    "termOfService": "Terms of Service",
    "copyright": "© 2025 Nguyễn Anh Tú. All rights reserved."
  },
  "Hero": {
    "title": "Empower Your Financial Future with Precision and Insight",
    "description": "Step into the world of strategic investment with Nguyễn Anh Tú, where deep expertise meets tailored financial vision. With a refined approach to wealth management and a commitment to long-term growth, Tú delivers personalized guidance that transforms opportunities into lasting success.",
    "contactNow": "Contact Now"
  },
  "BlogPage": {
    "title": "BLOGS",
    "seeAllBlogs": "See all blogs",
    "dateCreated": "Date Created"
  },
  "ProductPage": {
    "title": "PRODUCTS",
    "seeAllProducts": "See all products",
    "productDetails": "Product Details"
  },
  "ActionComponent": {
    "action": "Contact Now",
    "actionDescription": "Need advice on buying real estate"
  },
  "ClientFeedback": {
    "title": "Client Feedback"
  },
  "ContactMe": {
    "title": "Contact Me",
    "name": "Your Name",
    "validation": {
      "nameMustBe3or30Characters": "Must be 3 to 30 characters",
      "nameNotIncludeNumber": "only letters are allowed",
      "emailMustBeValid": "Enter a valid email address",
      "phoneValidate": "Must be 10 digits"
    },
    "email": "Your Email",
    "message": "Your Message",
    "sendMessage": "Send Message",
    "selectProject": "Select Project",
    "messagePlaceholder": "Example / Ví dụ:\n- Tôi là người Trung Quốc / I'm Chinese\n- Tôi là người Hàn Quốc / I'm Korean\n- Tôi là người Nhật / I'm Japanese\n- Tôi là người Thái Lan / I'm Thai\n- Tôi là người Singapore / I'm Singaporean\n- Tôi là người Pháp / I'm French\n- Tôi cần tư vấn về... / I need consultation about..."
  }
};
export default messages;