// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "IndexPage": {
    "title": "Nguyễn Anh Tú Investment Consultant"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "Navigation": {
    "home": "HOME",
    "about": "ABOUT",
    "product": "PRODUCT",
    "subMenuHeading": {
      "area": "Area",
      "products": "Products",
      "typeOfApartments": "Types of Apartments"
    },
    "blogs": "BLOGS",
    "contact": "CONTACT",
    "position": "Nguyễn Anh Tú Investment Consultant"
  },
  "Footer": {
    "home": "Home",
    "about": "About",
    "product": "Product",
    "blogs": "Blogs",
    "contact": "Contact",
    "privacyPolicy": "Privacy Policy",
    "termOfService": "Terms of Service",
    "copyright": "© 2025 Nguyễn Anh Tú. All rights reserved."
  },
  "Hero": {
    "title": "Empower Your Financial Future with Precision and Insight",
    "description": "Step into the world of strategic investment with Nguyễn Anh Tú, where deep expertise meets tailored financial vision. With a refined approach to wealth management and a commitment to long-term growth, Tú delivers personalized guidance that transforms opportunities into lasting success.",
    "contactNow": "Contact Now"
  },
  "BlogPage": {
    "title": "BLOGS",
    "seeAllBlogs": "See all blogs",
    "dateCreated": "Date Created",
    "searchBlogByTitle": "Search blog by title",
    "noBlogFound": "No blogs found matching your search.",
    "noBlogAvailable": "No blogs available.",
    "detail": {
      "home": "HOME",
      "blogs": "BLOGS",
      "author": "Author",
      "createDate": "Create Date",
      "information": "Blog Information"
    },
    "relatedBlogs": "RELATED BLOGS"
  },
  "ProductPage": {
    "title": "PRODUCTS",
    "seeAllProducts": "See all products",
    "productDetails": "Product Details",
    "noProductFound": "No products found",
    "filter": {
      "investor": "Investor",
      "project": "Project",
      "area": "Area",
      "typeOfApartment": "Type of Apartment",
      "all": "All",
      "allProjects": "All Projects",
      "clearAllFilters": "Clear All Filters"
    },
    "detail": {
      "area": "Area",
      "typeOfApartment": "Type of Apartment",
      "time": "Time",
      "information": "Information",
      "project": "Project",
      "in": "in",
      "home": "HOME",
      "products": "PRODUCTS"
    }
  },
  "ActionComponent": {
    "action": "Contact Now",
    "actionDescription": "Need advice on buying real estate"
  },
  "ClientFeedback": {
    "title": "Client Feedback"
  },
  "ContactMe": {
    "title": "Contact Me",
    "name": "Your Name",
    "validation": {
      "nameMustBe3or30Characters": "Must be 3 to 30 characters",
      "nameNotIncludeNumber": "only letters are allowed",
      "emailMustBeValid": "Enter a valid email address",
      "phoneValidate": "Must be 10 digits"
    },
    "email": "Your Email",
    "message": "Your Message",
    "sendMessage": "Send Message",
    "selectProject": "Select Project",
    "messagePlaceholder": "Example / Ví dụ:\n- Tôi là người Trung Quốc / I'm Chinese\n- Tôi là người Hàn Quốc / I'm Korean\n- Tôi là người Nhật / I'm Japanese\n- Tôi là người Thái Lan / I'm Thai\n- Tôi là người Singapore / I'm Singaporean\n- Tôi là người Pháp / I'm French\n- Tôi cần tư vấn về... / I need consultation about..."
  },
  "AboutPage": {
    "title": "TRUSTED COMPANION",
    "aboutIntroduce01": "Nguyen Anh Tu started his career in 2015—a time when Vietnam’s real estate market was shifting toward greater professionalism. By closely following the market for nearly 10 years, Tu has gained a practical perspective on market cycles and the factors that create real value in real estate.",
    "aboutIntroduce02": "Tu’s priorities are clear legal status, product quality, developer reputation, and a foundation for sustainable urban development. These are the core criteria for selecting and recommending the most suitable products for each client.",
    "aboutIntroduce03": "Tu is proud to be part of ERA Vietnam—an international real estate exchange that has successfully operated in many countries worldwide. ERA is currently the leading strategic distributor in Vietnam, with over 60 projects distributed nationwide. Thanks to this, Tu has access to a diverse range of properties and a comprehensive overview to compare, evaluate, and select products that truly match each client’s needs and goals.",
    "aboutIntroduce04": "Southern real estate: the value of merging Ho Chi Minh City’s mega-urban area; fertile lands such as Long An, Nhon Trach, Bien Hoa, Long Thanh, Phu My… From residential, commercial, to tourism properties… Work with Nguyen Anh Tu, your trusted companion !",
    "saySentence01": "“I always strive to create investment opportunities that are sustainable, luxurious, and refined—where financial value goes hand in hand with quality of life. Every property I select and recommend must meet high standards of profitability potential, strategic location, and, most importantly, align with the sophisticated lifestyle of clients who truly understand what they seek in real estate.”",
    "saySentence02": "Nguyễn Anh Tú is the top choice for discerning investors seeking a trustworthy partner—someone who not only understands the market but also appreciates each client’s unique sense of style and living preferences. With the refined perspective of a Vietnamese professional and a global mindset in finance and lifestyle, Tú goes beyond property introductions to offer lifestyle consulting—a long-term, sustainable vision.",
    "aboutTitle": "AN INVESTMENT CONSULTANT IS ALSO A VALUE CREATOR",
    "about1": "According to Nguyễn Anh Tú, a real estate investment consultant is not merely someone who introduces products, but someone who conveys the spirit and long-term vision behind every deal. An ideal property is not just about location or financial value—it reflects the lifestyle, personality, and aspirations of its owner. Choosing the right space to live or invest in is the first step toward building a prosperous and sustainable life—a place we don’t just ‘stay’ in, but truly call ‘home’.",
    "about2": "With a human-centered philosophy, Nguyễn Anh Tú always places the desires, feelings, and financial goals of each client at the heart of every consulting decision. Each product he introduces is not simply a piece of real estate—it is a part of a long-term strategy, personalized to reflect the lifestyle, aesthetics, and unique objectives of every client.",
    "about3": "Working with both passion and refined intuition, Nguyễn Anh Tú consistently strives to connect clients with assets that carry a personal imprint—opening the door to a world of living and investing that is not only effective but also emotionally fulfilling."
  },
  "Discover": {
    "title": "OUR TEAM",
    "description": "We are a group of innovate, experience, and proficient teams. You will love to collaborate with us."
  },
  "Admin": {
    "SideMenu": {
      "dashboard": "Dashboard",
      "blogs": "Blogs",
      "products": "Products",
      "users": "Users",
      "contacts": "Contacts",
      "logout": "Logout"
    },
    "Blog": {
      "namePage": "Blog Management",
      "create": "Create Blog",
      "edit": "Edit Blog",
      "title": "Title",
      "description": "Description",
      "author": "Author",
      "content": "Content",
      "image": "Image",
      "deleteTitle": "Delete Blog",
      "deleteMessage": "Are you sure you want to delete the blog {title}? This action cannot be undone.",
      "deleteSuccess": "Delete blog successfully",
      "deleteError": "Delete blog failed",
      "createSuccess": "Create blog successfully",
      "updateSuccess": "Update blog successfully",
      "noBlogAvailable": "No blogs available.",
      "noBlogFound": "No blogs found matching your search."
    },
    "Product": {
      "namePage": "Product Management",
      "create": "Create Product",
      "edit": "Edit Product",
      "name": "Name",
      "type": "Type",
      "area": "Area",
      "typeOfApartment": "Type of Apartment",
      "investor": "Investor",
      "acreage": "Acreage",
      "deleteTitle": "Delete Product",
      "deleteMessage": "Are you sure you want to delete the product {title}? This action cannot be undone.",
      "deleteSuccess": "Delete product successfully",
      "deleteError": "Delete product failed",
      "createSuccess": "Create product successfully",
      "updateSuccess": "Update product successfully",
      "pleaseInputRequirefield": "Please input all required fields",
      "typeOptions": {
        "default": "Select Type"
      },
      "mainImage": "Main Image",
      "mainImageDescription": "Select only 1 PNG/JPG image.",
      "listImages": "Image List",
      "listImagesDescription": "Select up to 10 PNG/JPG images. Selected: {count} images.",
      "editListImagesDescription": "Please select at least 1 and at most 10 PNG/JPG images.",
      "discription": "Detailed Description",
      "noProductFound": "No products found matching your search.",
      "noProductAvailable": "No products available."
    },
    "Contact": {
      "namePage": "Contact Management",
      "name": "Name",
      "email": "Email",
      "phone": "Phone Number",
      "message": "Message",
      "project": "Project",
      "exportExcel": "Export Excel",
      "exportExcelSuccess": "Export Excel successfully",
      "exportError": "Export Excel failed",
      "backToList": "Back to contact list",
      "information": "Contact Information",
      "noContactFound": "No contacts found matching your search.",
      "noContactAvailable": "No contacts available."
    },
    "Action": {
      "create": "Create New",
      "update": "Update",
      "delete": "Delete",
      "confirmDelete": "Are you sure you want to delete?",
      "cancel": "Cancel",
      "save": "Save",
      "edit": "Edit",
      "view": "View Details",
      "saving": "Saving...",
      "updating": "Updating...",
      "modal": {
        "changeTitle": "Do you want to save changes?",
        "changeMessage": "Data has changed, do you want to save or discard changes?",
        "confirm": "Confirm Changes",
        "cancel": "Discard Changes"
      }
    },
    "Search": {
      "blogs": "Search blogs by title",
      "products": "Search products by project name, location, or apartment type",
      "contacts": "Search contacts by name, email, phone number, or project"
    }
  }
};
export default messages;