// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "IndexPage": {
    "title": "next-intl example"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "Navigation": {
    "home": "HOME",
    "about": "ABOUT",
    "product": "PRODUCT",
    "subMenuHeading": {
      "area": "Area",
      "projects": "Projects",
      "typeOfApartments": "Types of Apartments"
    },
    "blogs": "BLOGS",
    "contact": "CONTACT",
    "position": "Nguyễn Anh Tú Investment Consultant"
  },
  "Footer": {
    "home": "Home",
    "about": "About",
    "product": "Product",
    "blogs": "Blogs",
    "contact": "Contact",
    "privacyPolicy": "Privacy Policy",
    "termOfService": "Terms of Service",
    "copyright": "© 2025 Nguyễn Anh Tú. All rights reserved."
  }
};
export default messages;